#!/usr/bin/env bash

# fetch git resource
[ "$TRACE" == "true" ] && set -x
set -e
set -o pipefail

source /opt/resource/git/common.sh

DEST_DIR="$1"

GIT_DEST_DIR="$(mktemp -d -t git-resource-destination.XXXXXX)"

/opt/resource/git/in "$GIT_DEST_DIR"


PAYLOAD=$(echo /tmp/git-resource-request.*)

load_pubkey $PAYLOAD
configure_git_ssl_verification $PAYLOAD
configure_credentials $PAYLOAD

# begin 
cd "$GIT_DEST_DIR"

[[ -f pom.xml ]] || { echo "There is no pom.xml in the git repo." >&2; exit 1; }

MAVEN_REPO=$DEST_DIR mvn -B --fail-never dependency:go-offline >&2

echo Downloaded $(du -hs $DEST_DIR | cut -f1) in $(find $DEST_DIR -type f | wc -l) files. >&2
